### PR TITLE
#150: Fixed permissions for docker credentials env file

### LINKED ISSUE #150: Wrong permissions for docker credentials env file
The docker credentials env file has wrong permissions, set [here](https://github.com/exasol/script-languages-container-tool/blob/d9b07cf4adbdc663efa0ef94afb058549f1940c3/exasol_script_languages_container_tool/starter_scripts/exaslct_within_docker_container.sh#L120). The permission should be set correctly.

### PR DESCRIPTION
**Pull request by tomuben**
Fixes #150 

Current `umask` prevents write access.
=> Remove usage of `umask` and set file permissions after creation and also after writing credentials (read-only)

### CODE REVIEW

File: exasol_script_languages_container_tool/starter_scripts/exaslct_within_docker_container_slim.sh [hunk 1]
```diff
@@ -46,12 +46,14 @@ DOCKER_SOCKET_MOUNT="$HOST_DOCKER_SOCKER_PATH:$CONTAINER_DOCKER_SOCKER_PATH"
...
 function create_env_file() {
   touch "$tmpfile_env"
+  chmod 600 "$tmpfile_env"
   if [ -n "${TARGET_DOCKER_PASSWORD-}" ]; then
     echo "TARGET_DOCKER_PASSWORD=$TARGET_DOCKER_PASSWORD" >> "$tmpfile_env"
   fi
   if [ -n "${SOURCE_DOCKER_PASSWORD-}" ]; then
     echo "SOURCE_DOCKER_PASSWORD=$SOURCE_DOCKER_PASSWORD" >> "$tmpfile_env"
   fi
+  chmod -w "$tmpfile_env"
```
Comment (kaklakariada) [inline exasol_script_languages_container_tool/starter_scripts/exaslct_within_docker_container_slim.sh:56]: What does option `-w` do?

**Review by kaklakariada — APPROVED** [review]

File: exasol_script_languages_container_tool/starter_scripts/exaslct_within_docker_container_slim.sh (hunk 1 above)
Comment (tkilias) [reply exasol_script_languages_container_tool/starter_scripts/exaslct_within_docker_container_slim.sh:56]:
```suggestion
  chmod  a-w "$tmpfile_env"
```

**Review by tkilias — APPROVED** [review]
